"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.syncPrimeran = exports.syncMakusi = exports.etbCatalog = exports.syncEtbOnly = exports.syncCatalogHttp = exports.dailySync = void 0;
var tmdb_1 = require("./sync/tmdb");
Object.defineProperty(exports, "dailySync", { enumerable: true, get: function () { return tmdb_1.dailySync; } });
Object.defineProperty(exports, "syncCatalogHttp", { enumerable: true, get: function () { return tmdb_1.syncCatalogHttp; } });
var etb_1 = require("./sync/etb");
Object.defineProperty(exports, "syncEtbOnly", { enumerable: true, get: function () { return etb_1.syncEtbOnly; } });
Object.defineProperty(exports, "etbCatalog", { enumerable: true, get: function () { return etb_1.etbCatalog; } });
var makusi_1 = require("./sync/makusi");
Object.defineProperty(exports, "syncMakusi", { enumerable: true, get: function () { return makusi_1.syncMakusi; } });
var primeran_1 = require("./sync/primeran");
Object.defineProperty(exports, "syncPrimeran", { enumerable: true, get: function () { return primeran_1.syncPrimeran; } });
